ContextErrorException: call_user_func() expects parameter 1 to be a valid callback
I was getting:

```
ContextErrorException: Warning: call_user_func() expects parameter 1 to be a valid callback, class 'my.serializer.handler.image' not found in vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php line 172
```

Removing `public="false"` fixed it.